export const breeds = [
    { name: "Любой", value: 1 },
    { name: "Британская короткошерстная кошка", value: 2 },
    { name: "Абиссинская кошка", value: 3 },
    { name: "Австралийский мист", value: 4 },
    { name: "Американский бобтейл", value: 5 },
    { name: "Курильский бобтейл", value: 6 },
    { name: "Персидская кошка", value: 7 },
    { name: "Русская голубая кошка", value: 8 },
    { name: "Сиамская кошка", value: 9 },
    { name: "Сибирская кошка", value: 10 },
    { name: "Тайская кошка", value: 11 },
    { name: "Тайский бобтейл", value: 12 },
    { name: "Чаузи", value: 13 },
    { name: "Японский бобтейл", value: 14 },
    { name: "Бурманская кошка", value: 15 },
    { name: "Мейн-кун", value: 16 },
    { name: "Американский кёрл", value: 17 },
    { name: "Бенгальская кошка", value: 18 },
    { name: "Гималайская кошка", value: 19 },
    { name: "Девон-рекс", value: 20 },
    { name: "Донской сфинкс", value: 21 },
    { name: "Мэнская кошка", value: 22 },
    { name: "Невская маскарадная кошка", value: 23 },
    { name: "Нибелунг", value: 24 },
    { name: "Ангорская кошка", value: 25 },
    { name: "Шартрез", value: 26 },
    { name: "Балинезийская кошка", value: 27 },
    { name: "Кимрик", value: 28 },
    { name: "Корат", value: 29 },
    { name: "Манчкин", value: 30 },
    { name: "Норвежская лесная кошка", value: 31 },
    { name: "Петерболд", value: 32 },
    { name: "Скоттиш-фолд", value: 33 },
    { name: "Сомалийская кошка", value: 34 },
    { name: "Турецкий ван", value: 35 },
    { name: "Форин вайт", value: 36 },
    { name: "Экзотическая кошка", value: 37 },
    { name: "Као мани", value: 38 },
    { name: "Йоркская шоколадная кошка", value: 39 },
    { name: "Египетская мау", value: 40 },
    { name: "Гавана браун", value: 41 },
    { name: "Бомбейская кошка", value: 42 },
    { name: "Канадский сфинкс", value: 43 },
    { name: "Корниш-рекс", value: 44 },
    { name: "Лаперм", value: 45 },
    { name: "Немецкий рекс", value: 46 },
    { name: "Оцикет", value: 47 },
    { name: "Рагамаффин", value: 48 },
    { name: "Рэгдолл", value: 49 },
    { name: "Саванна", value: 50 },
    { name: "Сноу-шу", value: 51 },
    { name: "Сококе", value: 52 },
    { name: "Тойгер", value: 53 },
    { name: "Тонкинская кошка", value: 54 },
    { name: "Цейлонская кошка", value: 55 },
    { name: "Шантильи тиффани", value: 56 },
    { name: "Эльф", value: 57 },
    { name: "Яванская кошка", value: 58 },
    { name: "Тиффани", value: 59 },
    { name: "Американская короткошерстная кошка", value: 60 },
    { name: "Анатолийская кошка", value: 61 },
    { name: "Бразильская короткошёрстная кошка", value: 62 },
    { name: "Европейская короткошерстная кошка", value: 63 },
    { name: "Калифорнийская сияющая кошка", value: 64 },
    { name: "Канаани", value: 65 },
    { name: "Карельский бобтейл", value: 66 },
    { name: "Наполеон", value: 67 },
    { name: "Орегон рекс", value: 68 },
    { name: "Ориентальная кошка", value: 69 },
    { name: "Охос азулес", value: 70 },
    { name: "Пиксибоб", value: 71 },
    { name: "Бирманская кошка", value: 72 },
    { name: "Сейшельская кошка", value: 73 },
    { name: "Селкирк-рекс", value: 74 },
    { name: "Серенгети", value: 75 },
    { name: "Сингапурская кошка", value: 76 },
    { name: "Уральский рекс", value: 77 },
    { name: "Хайленд-фолд", value: 78 },
    { name: "Украинский левкой", value: 79 },
    { name: "Меконгский бобтейл", value: 80 },
    { name: "Турецкая ангора", value: 81 },
    { name: "Шотландская кошка (скоттиш-фолд)", value: 82 },
    { name: "Британская длинношерстная кошка", value: 83 },
    { name: "Бурмилла ", value: 84 },
    { name: "Азиатская табби ", value: 85 },
    { name: "Беспородный", value: 86 },
    { name: "Минскин", value: 87 },
    { name: "Двэльф", value: 88 },
    { name: "Скоттиш-страйт", value: 89 },
];

export const ages = [
    { name: "Любой", value: 1 },
    { name: "Собаки", value: 2 },
    { name: "Новорожденные (1-2 недели)", value: 3 },
    { name: "Щенки (до 1 года)", value: 4 },
    { name: "Взрослые (1-6 лет)", value: 5 },
    { name: "Пожилые (старше 6 лет)", value: 6 },
    { name: "Кошки", value: 7 },
    { name: "Котенок (до 1 года)", value: 8 },
    { name: "Взрослые (1-7 лет)", value: 9 },
    { name: "Пожилые (Старше 7 лет)", value: 10 },
];

export const adTypes = [
    { name: "Любой", value: 1 },
    { name: "На продажу/Купить", value: 2 },
    { name: "Добрые руки/Отдам", value: 3 },
    { name: "Вязка", value: 4 },
    { name: "Потерявшиеся", value: 5 },
];

export const cats = [
    {
        image: "1.webp",
        icon: "photo_2022_05_02_15_54_17.jpg",
        name: "Мейн кун",
        city: "Москва",
        price: "80 Р",
        owner: "Вероника",
        article: "c1",
        available: true
    },
    {
        image: "2.webp",
        icon: "",
        name: "Продажа",
        city: "Москва",
        price: "40000 Р",
        owner: "Татьяна",
        article: "c2",
        available: true
    },
    {
        image: "3.webp",
        icon: "",
        name: "Продажа",
        city: "Москва",
        price: "40000 Р",
        owner: "Татьяна",
        article: "c3",
        available: true
    },
    {
        image: "4.webp",
        icon: "",
        name: "3,5 мес принцесса Мура ищет семью!",
        city: "Москва",
        price: "10 Р",
        owner: "Светлана",
        article: "c4",
        available: true
    },
    {
        image: "5.webp",
        icon: "",
        name: "Симон и Сима. Котята в добрые руки",
        city: "Москва",
        price: "Бесплатно",
        owner: "Светлана",
        article: "c5",
        available: true
    },
    {
        image: "6.webp",
        icon: "",
        name: "Маленькие котята в добрые руки",
        city: "Москва",
        price: "10 Р",
        owner: "Фекла",
        article: "c6",
        available: true
    },
    {
        image: "7.webp",
        icon: "photo_2022_05_02_15_54_17.jpg",
        name: "Уникальная Агата",
        city: "Москва",
        price: "Бесплатно",
        owner: "Зооцентр КиС",
        article: "c7",
        available: true
    }
];
export const genders = [
    { name: "Любой", value: 1 },
    { name: "Мальчик", value: 2 },
    { name: "Девочка", value: 3 },
];
export const colors = [
    { name: "Любой", value: 1 },
    { name: "Белый", value: 2 },
    { name: "Черный", value: 3 },
    { name: "Рыжий", value: 4 },
    { name: "Другой", value: 5 },
]
